spring:
  main:
    allow-bean-definition-overriding: true
  #Kafka Configuration
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        citizens-create-out:
          destination: create_citizens
          contentType: application/json
        citizens-update-out:
          destination: update_citizens
          contentType: application/json
        citizens-delete-out:
          destination: delete_citizens
          contentType: application/json
  #DATA SOURCE H2 in memory Configuration
  h2:
    console:
      enable: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2
    initialization-mode: always
  #JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false

#swagger configuration
base:
  package:
    swagger: com.goodcitizens.api